SELECT id_product FROM CARD_CONTRACT cc WHERE cc.ID_CONTRACT = 3297
sELECT * FROM CARD_CONTRACT cc
SELECT * from account
SELECT * FROM CARD_PRODUCT cp WHERE cp.ID_PRODUCT = 119
SELECT * FROM CARD_PRODUCT_ADDFL_DIC cpad
SELECT * FROM CARD_PRODUCT_ADDFL cpa WHERE cpa.ID_FIELD = 5 AND cpa.ID_OBJECT = 119
SELECT c.FIRST_NAME, c.MIDDLE_NAME, c.LAST_NAME, c.INN, c.DATE_BIRTH FROM CLIENTS c WHERE c.ID_CLIENT = 7245
SELECT * FROM CARD_CONTRACT cc
SELECT * FROM CONTRACT_MAIN cm
SELECT * FROM main

SELECT * FROM CLIENTS_ADDFL_DIC cad
SELECT * FROM CLIENTS_ADDFL_DIC cad WHERE cad.NAME_FIELD = 'Гражданство (подданство)'

SELECT * FROM RB_ABONENT ra
SELECT * FROM RB_CONTRACT_ADDFL_DIC rcad
SELECT * FROM RB_CONTRACT_ABONENT rca

SELECT * FROM RB_CONTRACT_ACC rca

SELECT rc.NUM_CONTRACT, rc.DATE_BEGIN, rc.DATE_END, (SELECT rcas.FIELD FROM RB_CONTRACT_ADDFL_STRING rcas WHERE rcas.ID_OBJECT = 4 AND rcas.ID_FIELD = 30) AS phone FROM RB_CONTRACT rc WHERE ID_CONTRACT = 4

SELECT field FROM RB_CONTRACT_ADDFL_STRING rcas WHERE  rcas.ID_OBJECT = (SELECT rc.ID_CONTRACT FROM RB_CONTRACT rc WHERE rc.ID_CLIENT = 7245) AND rcas.ID_FIELD = (SELECT rcad.ID_FIELD FROM RB_CONTRACT_ADDFL_DIC rcad WHERE rcad.NAME_FIELD = 'Мобильный для ДБО')

SELECT login FROM RB_ABONENT ra WHERE ra.ID_ABONENT = (SELECT rca.ID_ABONENT FROM RB_CONTRACT_ABONENT rca WHERE rca.ID_CONTRACT = 4)

SELECT * FROM CLIENTS c WHERE c.ID_CLIENT = 2095

    	SELECT cpa.FIELD_STRING FROM CARD_PRODUCT_ADDFL cpa
      WHERE cpa.ID_FIELD = 5 -- доп. аттрибут тип ПС
        AND cpa.ID_OBJECT = (SELECT id_product FROM CARD_CONTRACT cc WHERE cc.ID_CONTRACT = 3297)

SELECT * FROM OD_ACCOUNTS0 oa WHERE oa.ID_CLIENT = 7245