exec sp_executesql 
N'insert into RB_ABONENT
with ( ROWLOCK, UPDLOCK ) (LOGIN, NAME_ABONENT, STATE, NEXT_LOGON_CHANGE_PASSW, PASSWORD, EXPIRY_DATE_PASSW, TRY_LOGON, TYPE_ABONENT, ID_USER_EDIT, TIME_EDIT )
values (@LOGIN, @NAME_ABONENT, @STATE, @NEXT_LOGON_CHANGE_PASSW, @PASSWORD, @EXPIRY_DATE_PASSW, @TRY_LOGON, @TYPE_ABONENT, @ID_USER_EDIT, getdate())',

N'@LOGIN varchar(10),
@NAME_ABONENT varchar(31),
@STATE tinyint,
@NEXT_LOGON_CHANGE_PASSW tinyint,
@PASSWORD varbinary(32),
@EXPIRY_DATE_PASSW datetime,
@TRY_LOGON tinyint,
@TYPE_ABONENT tinyint,
@ID_USER_EDIT smallint',
@LOGIN='9272683933',
@NAME_ABONENT='Кузьменко Алексей Александрович',
@STATE=0,
@NEXT_LOGON_CHANGE_PASSW=0,
@PASSWORD=0x8D969EEF6ECAD3C29A3A629280E686CF0C3F5D5A86AFF3CA12020C923ADC6C92,
@EXPIRY_DATE_PASSW='2019-02-16 00:00:00',
@TRY_LOGON=0,
@TYPE_ABONENT=0,
@ID_USER_EDIT=2